Traceback (most recent call last):
  File "/Users/lillythomas/.pyenv/versions/3.8.9/envs/py38/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/lillythomas/.pyenv/versions/3.8.9/envs/py38/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/lillythomas/.pyenv/versions/3.8.9/envs/py38/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/lillythomas/.pyenv/versions/3.8.9/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/lillythomas/.pyenv/versions/3.8.9/envs/py38/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/lillythomas/.pyenv/versions/3.8.9/envs/py38/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/lillythomas/.pyenv/versions/3.8.9/envs/py38/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
state = geopandas.read_file(f"{data_dir}/karnataka_district/KA_subdistrict.shp")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m state [38;5;241m=[39m [43mgeopandas[49m[38;5;241m.[39mread_file([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mdata_dir[38;5;132;01m}[39;00m[38;5;124m/karnataka_district/KA_subdistrict.shp[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'geopandas' is not defined

